
import type { Metadata } from 'next';

// This is a special layout that does NOT use the main AppLayout
// It's for the public-facing note pages generated by the QR code feature.
// This prevents any workspace/authentication errors on the public page.

export const metadata: Metadata = {
  title: "Synapse Study Note",
  description: "An AI-generated note from Synapse Study.",
};

export default function NoteLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
            {children}
        </body>
    </html>
  );
}
